modLoader = "javafml"
loaderVersion = "[40,)"
issueTrackerURL = "${issues}"
license = "${license}"

[[mods]]
modId = "${modid}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${author}"
description = '''
${mod_description}
'''
logoFile = "${icon}"

[[dependencies.custommachinerycreate]]
modId = "forge"
mandatory = true
versionRange = "[40,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custommachinerycreate]]
modId = "minecraft"
mandatory = true
versionRange = "[${minecraft_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.custommachinerycreate]]
modId = "architectury"
mandatory = true
versionRange = "[${architectury_version},)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.custommachinerycreate]]
modId = "create"
mandatory = true
versionRange = "[${create_forge_version},)"
ordering = "NONE"
side = "BOTH"